%YAML 1.2
---
name: Youtube Script Generator
comment: An agent to generate youtube video scripts
model:
    # id: text-davinci-003
    id: gpt-3.5-turbo
    # id: claude-v1
prompt:
    - template: script_template.jinja